// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCHEMA_BENCH_FB_H_
#define FLATBUFFERS_GENERATED_SCHEMA_BENCH_FB_H_

#include "flatbuffers/flatbuffers.h"

namespace bench_fb {

struct Packet;
struct PacketBuilder;

struct Packet FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PacketBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TIMESTAMP = 6,
    VT_TEXT = 8
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  double timestamp() const {
    return GetField<double>(VT_TIMESTAMP, 0.0);
  }
  const flatbuffers::String *text() const {
    return GetPointer<const flatbuffers::String *>(VT_TEXT);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID) &&
           VerifyField<double>(verifier, VT_TIMESTAMP) &&
           VerifyOffset(verifier, VT_TEXT) &&
           verifier.VerifyString(text()) &&
           verifier.EndTable();
  }
};

struct PacketBuilder {
  typedef Packet Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Packet::VT_ID, id, 0);
  }
  void add_timestamp(double timestamp) {
    fbb_.AddElement<double>(Packet::VT_TIMESTAMP, timestamp, 0.0);
  }
  void add_text(flatbuffers::Offset<flatbuffers::String> text) {
    fbb_.AddOffset(Packet::VT_TEXT, text);
  }
  explicit PacketBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Packet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Packet>(end);
    return o;
  }
};

inline flatbuffers::Offset<Packet> CreatePacket(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    double timestamp = 0.0,
    flatbuffers::Offset<flatbuffers::String> text = 0) {
  PacketBuilder builder_(_fbb);
  builder_.add_timestamp(timestamp);
  builder_.add_id(id);
  builder_.add_text(text);
  return builder_.Finish();
}

inline flatbuffers::Offset<Packet> CreatePacketDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    double timestamp = 0.0,
    const char *text = nullptr) {
  auto text__ = text ? _fbb.CreateString(text) : 0;
  return bench_fb::CreatePacket(
      _fbb,
      id,
      timestamp,
      text__);
}

inline const bench_fb::Packet *GetPacket(const void *buf) {
  return flatbuffers::GetRoot<bench_fb::Packet>(buf);
}

inline const bench_fb::Packet *GetSizePrefixedPacket(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<bench_fb::Packet>(buf);
}

inline bool VerifyPacketBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<bench_fb::Packet>(nullptr);
}

inline bool VerifySizePrefixedPacketBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<bench_fb::Packet>(nullptr);
}

inline void FinishPacketBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<bench_fb::Packet> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPacketBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<bench_fb::Packet> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace bench_fb

#endif  // FLATBUFFERS_GENERATED_SCHEMA_BENCH_FB_H_
