// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_telemetry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_telemetry_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_telemetry_2eproto;
class Telemetry;
struct TelemetryDefaultTypeInternal;
extern TelemetryDefaultTypeInternal _Telemetry_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Telemetry* Arena::CreateMaybeMessage<::Telemetry>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Telemetry final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Telemetry) */ {
 public:
  inline Telemetry() : Telemetry(nullptr) {}
  ~Telemetry() override;
  explicit PROTOBUF_CONSTEXPR Telemetry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Telemetry(const Telemetry& from);
  Telemetry(Telemetry&& from) noexcept
    : Telemetry() {
    *this = ::std::move(from);
  }

  inline Telemetry& operator=(const Telemetry& from) {
    CopyFrom(from);
    return *this;
  }
  inline Telemetry& operator=(Telemetry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Telemetry& default_instance() {
    return *internal_default_instance();
  }
  static inline const Telemetry* internal_default_instance() {
    return reinterpret_cast<const Telemetry*>(
               &_Telemetry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Telemetry& a, Telemetry& b) {
    a.Swap(&b);
  }
  inline void Swap(Telemetry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Telemetry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Telemetry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Telemetry>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Telemetry& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Telemetry& from) {
    Telemetry::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Telemetry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Telemetry";
  }
  protected:
  explicit Telemetry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 9,
    kActionLogFieldNumber = 10,
    kTimestampFieldNumber = 1,
    kPosXFieldNumber = 3,
    kPosYFieldNumber = 4,
    kSessionIdFieldNumber = 2,
    kHealthFieldNumber = 6,
    kPosZFieldNumber = 5,
    kAmmoFieldNumber = 7,
    kIsActiveFieldNumber = 8,
  };
  // string username = 9;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string action_log = 10;
  void clear_action_log();
  const std::string& action_log() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_action_log(ArgT0&& arg0, ArgT... args);
  std::string* mutable_action_log();
  PROTOBUF_NODISCARD std::string* release_action_log();
  void set_allocated_action_log(std::string* action_log);
  private:
  const std::string& _internal_action_log() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_action_log(const std::string& value);
  std::string* _internal_mutable_action_log();
  public:

  // uint64 timestamp = 1;
  void clear_timestamp();
  uint64_t timestamp() const;
  void set_timestamp(uint64_t value);
  private:
  uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(uint64_t value);
  public:

  // double pos_x = 3;
  void clear_pos_x();
  double pos_x() const;
  void set_pos_x(double value);
  private:
  double _internal_pos_x() const;
  void _internal_set_pos_x(double value);
  public:

  // double pos_y = 4;
  void clear_pos_y();
  double pos_y() const;
  void set_pos_y(double value);
  private:
  double _internal_pos_y() const;
  void _internal_set_pos_y(double value);
  public:

  // uint32 session_id = 2;
  void clear_session_id();
  uint32_t session_id() const;
  void set_session_id(uint32_t value);
  private:
  uint32_t _internal_session_id() const;
  void _internal_set_session_id(uint32_t value);
  public:

  // float health = 6;
  void clear_health();
  float health() const;
  void set_health(float value);
  private:
  float _internal_health() const;
  void _internal_set_health(float value);
  public:

  // double pos_z = 5;
  void clear_pos_z();
  double pos_z() const;
  void set_pos_z(double value);
  private:
  double _internal_pos_z() const;
  void _internal_set_pos_z(double value);
  public:

  // int32 ammo = 7;
  void clear_ammo();
  int32_t ammo() const;
  void set_ammo(int32_t value);
  private:
  int32_t _internal_ammo() const;
  void _internal_set_ammo(int32_t value);
  public:

  // bool is_active = 8;
  void clear_is_active();
  bool is_active() const;
  void set_is_active(bool value);
  private:
  bool _internal_is_active() const;
  void _internal_set_is_active(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Telemetry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr action_log_;
    uint64_t timestamp_;
    double pos_x_;
    double pos_y_;
    uint32_t session_id_;
    float health_;
    double pos_z_;
    int32_t ammo_;
    bool is_active_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_telemetry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Telemetry

// uint64 timestamp = 1;
inline void Telemetry::clear_timestamp() {
  _impl_.timestamp_ = uint64_t{0u};
}
inline uint64_t Telemetry::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint64_t Telemetry::timestamp() const {
  // @@protoc_insertion_point(field_get:Telemetry.timestamp)
  return _internal_timestamp();
}
inline void Telemetry::_internal_set_timestamp(uint64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void Telemetry::set_timestamp(uint64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:Telemetry.timestamp)
}

// uint32 session_id = 2;
inline void Telemetry::clear_session_id() {
  _impl_.session_id_ = 0u;
}
inline uint32_t Telemetry::_internal_session_id() const {
  return _impl_.session_id_;
}
inline uint32_t Telemetry::session_id() const {
  // @@protoc_insertion_point(field_get:Telemetry.session_id)
  return _internal_session_id();
}
inline void Telemetry::_internal_set_session_id(uint32_t value) {
  
  _impl_.session_id_ = value;
}
inline void Telemetry::set_session_id(uint32_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:Telemetry.session_id)
}

// double pos_x = 3;
inline void Telemetry::clear_pos_x() {
  _impl_.pos_x_ = 0;
}
inline double Telemetry::_internal_pos_x() const {
  return _impl_.pos_x_;
}
inline double Telemetry::pos_x() const {
  // @@protoc_insertion_point(field_get:Telemetry.pos_x)
  return _internal_pos_x();
}
inline void Telemetry::_internal_set_pos_x(double value) {
  
  _impl_.pos_x_ = value;
}
inline void Telemetry::set_pos_x(double value) {
  _internal_set_pos_x(value);
  // @@protoc_insertion_point(field_set:Telemetry.pos_x)
}

// double pos_y = 4;
inline void Telemetry::clear_pos_y() {
  _impl_.pos_y_ = 0;
}
inline double Telemetry::_internal_pos_y() const {
  return _impl_.pos_y_;
}
inline double Telemetry::pos_y() const {
  // @@protoc_insertion_point(field_get:Telemetry.pos_y)
  return _internal_pos_y();
}
inline void Telemetry::_internal_set_pos_y(double value) {
  
  _impl_.pos_y_ = value;
}
inline void Telemetry::set_pos_y(double value) {
  _internal_set_pos_y(value);
  // @@protoc_insertion_point(field_set:Telemetry.pos_y)
}

// double pos_z = 5;
inline void Telemetry::clear_pos_z() {
  _impl_.pos_z_ = 0;
}
inline double Telemetry::_internal_pos_z() const {
  return _impl_.pos_z_;
}
inline double Telemetry::pos_z() const {
  // @@protoc_insertion_point(field_get:Telemetry.pos_z)
  return _internal_pos_z();
}
inline void Telemetry::_internal_set_pos_z(double value) {
  
  _impl_.pos_z_ = value;
}
inline void Telemetry::set_pos_z(double value) {
  _internal_set_pos_z(value);
  // @@protoc_insertion_point(field_set:Telemetry.pos_z)
}

// float health = 6;
inline void Telemetry::clear_health() {
  _impl_.health_ = 0;
}
inline float Telemetry::_internal_health() const {
  return _impl_.health_;
}
inline float Telemetry::health() const {
  // @@protoc_insertion_point(field_get:Telemetry.health)
  return _internal_health();
}
inline void Telemetry::_internal_set_health(float value) {
  
  _impl_.health_ = value;
}
inline void Telemetry::set_health(float value) {
  _internal_set_health(value);
  // @@protoc_insertion_point(field_set:Telemetry.health)
}

// int32 ammo = 7;
inline void Telemetry::clear_ammo() {
  _impl_.ammo_ = 0;
}
inline int32_t Telemetry::_internal_ammo() const {
  return _impl_.ammo_;
}
inline int32_t Telemetry::ammo() const {
  // @@protoc_insertion_point(field_get:Telemetry.ammo)
  return _internal_ammo();
}
inline void Telemetry::_internal_set_ammo(int32_t value) {
  
  _impl_.ammo_ = value;
}
inline void Telemetry::set_ammo(int32_t value) {
  _internal_set_ammo(value);
  // @@protoc_insertion_point(field_set:Telemetry.ammo)
}

// bool is_active = 8;
inline void Telemetry::clear_is_active() {
  _impl_.is_active_ = false;
}
inline bool Telemetry::_internal_is_active() const {
  return _impl_.is_active_;
}
inline bool Telemetry::is_active() const {
  // @@protoc_insertion_point(field_get:Telemetry.is_active)
  return _internal_is_active();
}
inline void Telemetry::_internal_set_is_active(bool value) {
  
  _impl_.is_active_ = value;
}
inline void Telemetry::set_is_active(bool value) {
  _internal_set_is_active(value);
  // @@protoc_insertion_point(field_set:Telemetry.is_active)
}

// string username = 9;
inline void Telemetry::clear_username() {
  _impl_.username_.ClearToEmpty();
}
inline const std::string& Telemetry::username() const {
  // @@protoc_insertion_point(field_get:Telemetry.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Telemetry::set_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Telemetry.username)
}
inline std::string* Telemetry::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:Telemetry.username)
  return _s;
}
inline const std::string& Telemetry::_internal_username() const {
  return _impl_.username_.Get();
}
inline void Telemetry::_internal_set_username(const std::string& value) {
  
  _impl_.username_.Set(value, GetArenaForAllocation());
}
inline std::string* Telemetry::_internal_mutable_username() {
  
  return _impl_.username_.Mutable(GetArenaForAllocation());
}
inline std::string* Telemetry::release_username() {
  // @@protoc_insertion_point(field_release:Telemetry.username)
  return _impl_.username_.Release();
}
inline void Telemetry::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  _impl_.username_.SetAllocated(username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Telemetry.username)
}

// string action_log = 10;
inline void Telemetry::clear_action_log() {
  _impl_.action_log_.ClearToEmpty();
}
inline const std::string& Telemetry::action_log() const {
  // @@protoc_insertion_point(field_get:Telemetry.action_log)
  return _internal_action_log();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Telemetry::set_action_log(ArgT0&& arg0, ArgT... args) {
 
 _impl_.action_log_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Telemetry.action_log)
}
inline std::string* Telemetry::mutable_action_log() {
  std::string* _s = _internal_mutable_action_log();
  // @@protoc_insertion_point(field_mutable:Telemetry.action_log)
  return _s;
}
inline const std::string& Telemetry::_internal_action_log() const {
  return _impl_.action_log_.Get();
}
inline void Telemetry::_internal_set_action_log(const std::string& value) {
  
  _impl_.action_log_.Set(value, GetArenaForAllocation());
}
inline std::string* Telemetry::_internal_mutable_action_log() {
  
  return _impl_.action_log_.Mutable(GetArenaForAllocation());
}
inline std::string* Telemetry::release_action_log() {
  // @@protoc_insertion_point(field_release:Telemetry.action_log)
  return _impl_.action_log_.Release();
}
inline void Telemetry::set_allocated_action_log(std::string* action_log) {
  if (action_log != nullptr) {
    
  } else {
    
  }
  _impl_.action_log_.SetAllocated(action_log, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.action_log_.IsDefault()) {
    _impl_.action_log_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Telemetry.action_log)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
