// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TELEMETRY_MYBENCH_H_
#define FLATBUFFERS_GENERATED_TELEMETRY_MYBENCH_H_

#include "flatbuffers/flatbuffers.h"

namespace MyBench {

struct Telemetry;
struct TelemetryBuilder;

inline const flatbuffers::TypeTable *TelemetryTypeTable();

struct Telemetry FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TelemetryBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return TelemetryTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TIMESTAMP = 4,
    VT_SESSION_ID = 6,
    VT_POS_X = 8,
    VT_POS_Y = 10,
    VT_POS_Z = 12,
    VT_HEALTH = 14,
    VT_AMMO = 16,
    VT_IS_ACTIVE = 18,
    VT_USERNAME = 20,
    VT_ACTION_LOG = 22
  };
  uint64_t timestamp() const {
    return GetField<uint64_t>(VT_TIMESTAMP, 0);
  }
  uint32_t session_id() const {
    return GetField<uint32_t>(VT_SESSION_ID, 0);
  }
  double pos_x() const {
    return GetField<double>(VT_POS_X, 0.0);
  }
  double pos_y() const {
    return GetField<double>(VT_POS_Y, 0.0);
  }
  double pos_z() const {
    return GetField<double>(VT_POS_Z, 0.0);
  }
  float health() const {
    return GetField<float>(VT_HEALTH, 0.0f);
  }
  int32_t ammo() const {
    return GetField<int32_t>(VT_AMMO, 0);
  }
  bool is_active() const {
    return GetField<uint8_t>(VT_IS_ACTIVE, 0) != 0;
  }
  const flatbuffers::String *username() const {
    return GetPointer<const flatbuffers::String *>(VT_USERNAME);
  }
  const flatbuffers::String *action_log() const {
    return GetPointer<const flatbuffers::String *>(VT_ACTION_LOG);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TIMESTAMP) &&
           VerifyField<uint32_t>(verifier, VT_SESSION_ID) &&
           VerifyField<double>(verifier, VT_POS_X) &&
           VerifyField<double>(verifier, VT_POS_Y) &&
           VerifyField<double>(verifier, VT_POS_Z) &&
           VerifyField<float>(verifier, VT_HEALTH) &&
           VerifyField<int32_t>(verifier, VT_AMMO) &&
           VerifyField<uint8_t>(verifier, VT_IS_ACTIVE) &&
           VerifyOffset(verifier, VT_USERNAME) &&
           verifier.VerifyString(username()) &&
           VerifyOffset(verifier, VT_ACTION_LOG) &&
           verifier.VerifyString(action_log()) &&
           verifier.EndTable();
  }
};

struct TelemetryBuilder {
  typedef Telemetry Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_timestamp(uint64_t timestamp) {
    fbb_.AddElement<uint64_t>(Telemetry::VT_TIMESTAMP, timestamp, 0);
  }
  void add_session_id(uint32_t session_id) {
    fbb_.AddElement<uint32_t>(Telemetry::VT_SESSION_ID, session_id, 0);
  }
  void add_pos_x(double pos_x) {
    fbb_.AddElement<double>(Telemetry::VT_POS_X, pos_x, 0.0);
  }
  void add_pos_y(double pos_y) {
    fbb_.AddElement<double>(Telemetry::VT_POS_Y, pos_y, 0.0);
  }
  void add_pos_z(double pos_z) {
    fbb_.AddElement<double>(Telemetry::VT_POS_Z, pos_z, 0.0);
  }
  void add_health(float health) {
    fbb_.AddElement<float>(Telemetry::VT_HEALTH, health, 0.0f);
  }
  void add_ammo(int32_t ammo) {
    fbb_.AddElement<int32_t>(Telemetry::VT_AMMO, ammo, 0);
  }
  void add_is_active(bool is_active) {
    fbb_.AddElement<uint8_t>(Telemetry::VT_IS_ACTIVE, static_cast<uint8_t>(is_active), 0);
  }
  void add_username(flatbuffers::Offset<flatbuffers::String> username) {
    fbb_.AddOffset(Telemetry::VT_USERNAME, username);
  }
  void add_action_log(flatbuffers::Offset<flatbuffers::String> action_log) {
    fbb_.AddOffset(Telemetry::VT_ACTION_LOG, action_log);
  }
  explicit TelemetryBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Telemetry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Telemetry>(end);
    return o;
  }
};

inline flatbuffers::Offset<Telemetry> CreateTelemetry(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    uint32_t session_id = 0,
    double pos_x = 0.0,
    double pos_y = 0.0,
    double pos_z = 0.0,
    float health = 0.0f,
    int32_t ammo = 0,
    bool is_active = false,
    flatbuffers::Offset<flatbuffers::String> username = 0,
    flatbuffers::Offset<flatbuffers::String> action_log = 0) {
  TelemetryBuilder builder_(_fbb);
  builder_.add_pos_z(pos_z);
  builder_.add_pos_y(pos_y);
  builder_.add_pos_x(pos_x);
  builder_.add_timestamp(timestamp);
  builder_.add_action_log(action_log);
  builder_.add_username(username);
  builder_.add_ammo(ammo);
  builder_.add_health(health);
  builder_.add_session_id(session_id);
  builder_.add_is_active(is_active);
  return builder_.Finish();
}

inline flatbuffers::Offset<Telemetry> CreateTelemetryDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t timestamp = 0,
    uint32_t session_id = 0,
    double pos_x = 0.0,
    double pos_y = 0.0,
    double pos_z = 0.0,
    float health = 0.0f,
    int32_t ammo = 0,
    bool is_active = false,
    const char *username = nullptr,
    const char *action_log = nullptr) {
  auto username__ = username ? _fbb.CreateString(username) : 0;
  auto action_log__ = action_log ? _fbb.CreateString(action_log) : 0;
  return MyBench::CreateTelemetry(
      _fbb,
      timestamp,
      session_id,
      pos_x,
      pos_y,
      pos_z,
      health,
      ammo,
      is_active,
      username__,
      action_log__);
}

inline const flatbuffers::TypeTable *TelemetryTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_ULONG, 0, -1 },
    { flatbuffers::ET_UINT, 0, -1 },
    { flatbuffers::ET_DOUBLE, 0, -1 },
    { flatbuffers::ET_DOUBLE, 0, -1 },
    { flatbuffers::ET_DOUBLE, 0, -1 },
    { flatbuffers::ET_FLOAT, 0, -1 },
    { flatbuffers::ET_INT, 0, -1 },
    { flatbuffers::ET_BOOL, 0, -1 },
    { flatbuffers::ET_STRING, 0, -1 },
    { flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "timestamp",
    "session_id",
    "pos_x",
    "pos_y",
    "pos_z",
    "health",
    "ammo",
    "is_active",
    "username",
    "action_log"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 10, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const MyBench::Telemetry *GetTelemetry(const void *buf) {
  return flatbuffers::GetRoot<MyBench::Telemetry>(buf);
}

inline const MyBench::Telemetry *GetSizePrefixedTelemetry(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<MyBench::Telemetry>(buf);
}

inline bool VerifyTelemetryBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MyBench::Telemetry>(nullptr);
}

inline bool VerifySizePrefixedTelemetryBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MyBench::Telemetry>(nullptr);
}

inline void FinishTelemetryBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MyBench::Telemetry> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTelemetryBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MyBench::Telemetry> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace MyBench

#endif  // FLATBUFFERS_GENERATED_TELEMETRY_MYBENCH_H_
